Feature/UDV-37-base-repository
UDV-Benefits-Cafeteria/benefits-cafeteria-backend pull request #10
Opened 2024-09-28 14:13 UTC by Karasik876

2024-09-28 15:48 UTC, Materacl requested changes

2024-09-28 15:48 UTC, Materacl commented on alembic/env.py
> +config.set_section_option(section, "DB_PASS", settings.POSTGRES_PASSWORD)
Никак нельзя уменьшить повторы?

2024-09-28 15:48 UTC, Materacl commented on src/api/v1/default.py
> +from src.schemas.benefit import BenefitCreate, BenefitRead, BenefitUpdate
Импортируй не так, а так:
import src.schemas.benefit as schemas - так понятнее, что это и откуда;
потом используй schemas.benefit.BenefitCreate
и так со всем

2024-09-28 15:48 UTC, Materacl commented on src/api/v1/default.py
> +    benefits_service: Annotated[BenefitsService, Depends(get_benefits_service)],
Почему разные названия, то dependency, то get_...

2024-09-28 15:48 UTC, Materacl commented on src/api/v1/default.py
Сделай пометку в комментарии, что это тестовые эндопинты

2024-09-28 15:48 UTC, Materacl commented on src/api/v1/dependencies.py
> +def get_benefits_service():
Мне такой вариант названия больше нравится

2024-09-28 15:48 UTC, Materacl commented on src/services/benefits.py
тут надо еще много менять, но видимо это временно

2024-09-28 15:48 UTC, Materacl commented on src/utils/repository.py
> +    async def add_one(self, data: T) -> int:
Надо add_many

2024-09-28 15:48 UTC, Materacl commented on src/utils/repository.py
> +    model = None
Добавить типизацию

2024-09-28 15:48 UTC, Materacl commented on src/utils/repository.py
> +    async def find_one(self, id: int):
Добавить типизацию возвращаемых значений

2024-09-28 18:52 UTC, Karasik876 commented on src/utils/repository.py
> +                    selectinload(self.model.images),
Убрать selectinload(self.model.images) из базового репозитория

2024-09-29 09:14 UTC, StalinidzeCorp commented on alembic/env.py
> +config.set_section_option(section, "DB_PASS", settings.POSTGRES_PASSWORD)
Нельзя ли просто взять DB_URL из settings вместо того, чтобы создавать новую?

2024-10-03 11:01 UTC, Materacl approved these changes

2024-10-03 11:01 UTC, merged