Feature/UDV-39-models
UDV-Benefits-Cafeteria/benefits-cafeteria-backend pull request #9
Opened 2024-09-23 18:47 UTC by Karasik876

2024-09-23 18:51 UTC, Karasik876 commented on src/models/payments.py
> +    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
ondelete="CASCADE" лучше

2024-09-24 07:26 UTC, StalinidzeCorp commented on src/models/costs.py
> +    level_cost: Mapped[str] = mapped_column(String)
Должно быть int, иначе как мы будем считать? Текст сравнивать?

2024-09-24 07:27 UTC, StalinidzeCorp commented on src/models/costs.py
> +    level_cost: Mapped[str] = mapped_column(String)
равнозначно полю experience в user

2024-09-24 07:27 UTC, StalinidzeCorp commented on src/models/costs.py
> +# как будем обрабатывать ситуацию с несколькими стоимостями? допустим сотрудник работает больше 3 лет, ему что-то доступно бесплатно
меньшая стоимость вперед, если она доступна

2024-09-24 07:29 UTC, StalinidzeCorp commented on src/models/payments.py
> +    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
Вообще удаление пользователей не предусмотрено, так что не так важно

2024-09-24 07:31 UTC, StalinidzeCorp commented on src/models/users.py
> +    hired_at: Mapped[DateTime] = mapped_column(DateTime)
Важно ли нам время? Может просто Date?

2024-09-24 07:32 UTC, StalinidzeCorp commented on src/models/users.py
> +    )
Зачем 2 раза?

2024-09-24 07:33 UTC, StalinidzeCorp commented on src/models/users.py
> +        return delta.days // 30
Тоже самое для уровня нужно

2024-09-24 07:35 UTC, StalinidzeCorp commented on src/models/users.py
> +        return delta.days // 30
Я думаю experience это опыт, значит это дни, возможно стоит сделать и для уровня и для опыта 2 проперти?

2024-09-24 16:20 UTC, Materacl requested changes

2024-09-24 16:20 UTC, Materacl commented on src/models/benefits.py
> +    # можно добавить поле стоимости в реальной валюте, скрытное для пользователя, им будет пользоваться hr
Нужно добавить.

2024-09-24 16:20 UTC, Materacl commented on src/models/benefits.py
> +    completed = "completed"  # Завершен
Constants: Constants are usually defined on a module level and written in all capital letters with underscores separating words. Examples include MAX_OVERFLOW and TOTAL.

Источник: [PEP 8 — Naming Conventions](https://peps.python.org/pep-0008/#constants).

Применение этого правила к перечислениям означает, что члены перечисления (Enum) должны именоваться заглавными буквами с использованием подчеркиваний для разделения слов.

2024-09-24 16:20 UTC, Materacl commented on src/models/benefits.py
> +    )  # что тут должно храниться?
Информация для hr`ов. Текст в общем

2024-09-24 16:20 UTC, Materacl commented on src/models/benefits.py
Общие рекомендации: Располагай колонки в модели в зависимости от важности, настрой repr_cols_num и repr_cols для логирования красивого

2024-09-24 16:20 UTC, Materacl commented on src/models/payments.py
> +    __tablename__ = "coinpayments"
Лучше snake_case

2024-09-24 16:20 UTC, Materacl commented on src/models/benefits.py
> +    __tablename__ = "benefitscategories"
snake_case

2024-09-24 16:20 UTC, Materacl commented on src/models/applications.py
> +    from models import Benefit, User
Это точно необходимо?

2024-09-28 10:26 UTC, Materacl requested changes

2024-09-28 12:03 UTC, Materacl approved these changes

2024-09-28 12:03 UTC, merged